fix: sonarcloud security hotspots
TransbankDevelopers/transbank-plugin-virtuemart-webpay-rest pull request #11
Opened 2023-08-24 22:41 UTC by isabellaahc

This PR includes total reviews about sonarcloud security hotspots.

Changelog: 

- [x] Add rel=noopener on modal links 
- [x] Add https to virtuemart versions URL
- [x] Add script bootstrap url with integrity attribute
- [x] Replace session_id function by session_regenerate_id on emptyCart function
- [x] Add sonarcloud properties file to exclude docker folder and log4php library from sonar cloud analysis

Evidence install plugin and modal status: 
<img width="1472" alt="Captura de pantalla 2023-08-14 a la(s) 16 17 47" src="https://github.com/TransbankDevelopers/transbank-plugin-virtuemart-webpay-rest/assets/16402208/bdbd3659-8ade-4ac0-b349-663bea620d48">
![Captura de pantalla 2023-08-24 a la(s) 18 21 00](https://github.com/TransbankDevelopers/transbank-plugin-virtuemart-webpay-rest/assets/16402208/878ca89a-6e90-4d19-9ca1-a6ab67657706)
![Captura de pantalla 2023-08-24 a la(s) 18 21 23](https://github.com/TransbankDevelopers/transbank-plugin-virtuemart-webpay-rest/assets/16402208/ecd63efa-f4ac-4823-aefb-c175b4364067)
![Captura de pantalla 2023-08-24 a la(s) 18 22 20](https://github.com/TransbankDevelopers/transbank-plugin-virtuemart-webpay-rest/assets/16402208/642b1d28-08be-40a6-b655-0b768af2914b)

https://github.com/TransbankDevelopers/transbank-plugin-virtuemart-webpay-rest/assets/16402208/fd225c8d-3dff-448c-9b02-264ed6c59ee8

https://github.com/TransbankDevelopers/transbank-plugin-virtuemart-webpay-rest/assets/16402208/8441cf28-fe75-499a-8dee-2592f7c184e2

2023-08-25 21:17 UTC, mastudillot commented on src/transbank_webpay_rest/composer.json
> +        "transbank/transbank-sdk": "~2.0"
This must be two commits

2023-08-25 21:18 UTC, mastudillot commented on .sonarcloud.properties
> +sonar.exclusions=docker-virtuemart3, src/transbank_webpay_rest/library/log4php/**
Same, this must be two commits

2023-08-25 21:21 UTC, mastudillot requested changes
Separate the confirmations from the files where I left a comment

2023-08-28 23:59 UTC, victormendoza96 approved these changes

2023-08-28 23:59 UTC, victormendoza96 commented on .sonarcloud.properties
> +sonar.exclusions=docker-virtuemart3
missing empty line

2023-08-28 23:59 UTC, victormendoza96 commented on .sonarcloud.properties
> +sonar.exclusions=docker-virtuemart3, src/transbank_webpay_rest/library/log4php/**
empty line

2023-08-29 13:17 UTC, tribiec approved these changes
LGTM!

2023-08-29 15:56 UTC, merged