refactor: code refactoring in HealthCheck.php
TransbankDevelopers/transbank-plugin-virtuemart-webpay-rest pull request #17
Opened 2024-08-27 15:43 UTC by DiegoHBustamante

This version includes the following change:

- Code refactoring HealthCheck.php.
- Delete unused code.
- Code simplificaction.
<img width="1325" alt="Captura de pantalla 2024-08-27 a la(s) 11 28 53 a  m" src="https://github.com/user-attachments/assets/1b9d0b40-2518-4e52-b67d-e779f63fe3ad">

2024-08-27 20:34 UTC, Matiasnickolas commented on src/transbank_webpay_rest/library/HealthCheck.php
> +        $this->versioninfo = [
is necessary set this `versionInfo` as an attribute? or can return this directly

2024-08-27 20:34 UTC, Matiasnickolas commented on src/transbank_webpay_rest/library/HealthCheck.php
> +     * Gets the currently installed Virtuemart version.
this returns last virtuemart version, not the installed version

2024-08-27 20:34 UTC, Matiasnickolas commented on src/transbank_webpay_rest/library/HealthCheck.php
> +            exit;
is safe use exit instead return?

2024-08-27 21:33 UTC, mastudillot requested changes
add types in variable and functions

2024-08-27 21:33 UTC, mastudillot commented on src/transbank_webpay_rest/library/HealthCheck.php
>      private function getValidatephp()
Use a descriptive name, is a get or a validate function?

2024-08-28 21:09 UTC, mvarlic approved these changes
LGTM!

2024-08-29 18:49 UTC, Matiasnickolas commented on src/transbank_webpay_rest/library/HealthCheck.php
> +            'current_plugin_version' => $ecommerceInfo ? $ecommerceInfo['current_plugin_version'] : 'ERROR: No se pudo recuperar la versión de Ecommerce',
This error message is related to ecommerce version or tbk plugin version?

2024-08-30 21:37 UTC, mastudillot approved these changes
LGTM

2024-08-30 21:39 UTC, merged